# Generated by Django 6.1.1 on 2026-09-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('admin', 'Librarian / Admin')], default='student', max_length=20),
        ),
    ]
