# Generated by Django 6.1.1 on 2026-09-20 09:55

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_studentprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='taught_modules',
            field=models.ManyToManyField(blank=True, help_text="Modules this lecturer teaches. Only used when role is 'lecturer'.", related_name='lecturers', to='repository.course'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_pdf',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='resources/%Y/%m/%d/'),
        ),
    ]
