import type { User, Resource, Submission, Notification } from './types';

export const DEMO_USERS: User[] = [
  {
    id: 'u-student-1',
    name: 'Mwansa Kapemba',
    email: 'mwansa.kapemba@students.cavendish.ac.zm',
    role: 'student',
    studentId: 'CUZ/2022/CS/0142',
    programme: 'BSc Computer Science',
    school: 'School of Computing and Information Technology',
    yearOfStudy: 3,
    status: 'active',
    dateJoined: '2022-08-15',
    submissionsCount: 3,
    downloadsCount: 47,
    bookmarksCount: 12,
  },
  {
    id: 'u-lecturer-1',
    name: 'Dr. Chanda Musonda',
    email: 'c.musonda@cavendish.ac.zm',
    role: 'lecturer',
    staffId: 'CUZ/STF/0034',
    department: 'Department of Computing',
    school: 'School of Computing and Information Technology',
    status: 'active',
    dateJoined: '2018-01-10',
  },
  {
    id: 'u-admin-1',
    name: 'Ms. Thandiwe Mwape',
    email: 'library@cavendish.ac.zm',
    role: 'admin',
    staffId: 'CUZ/LIB/0001',
    department: 'Library & Academic Resources',
    school: 'University Library',
    status: 'active',
    dateJoined: '2016-03-01',
  },
];

export const SCHOOLS = [
  'School of Computing and Information Technology',
  'School of Business',
  'School of Law',
  'School of Social Sciences',
];

export const PROGRAMMES: Record<string, string[]> = {
  'School of Computing and Information Technology': [
    'BSc Computer Science',
    'BSc Information Technology',
    'BSc Software Engineering',
    'BSc Data Science',
  ],
  'School of Business': [
    'BSc Business Administration',
    'BSc Accounting & Finance',
    'BSc Marketing',
    'BSc Human Resource Management',
  ],
  'School of Law': ['LLB Law', 'LLB Law with Business'],
  'School of Social Sciences': [
    'BSc Psychology',
    'BSc Sociology',
    'BSc Public Administration',
  ],
};

export const RESOURCE_TYPE_LABELS: Record<string, string> = {
  'lecture-notes': 'Lecture Notes',
  'past-paper': 'Past Paper',
  'dissertation': 'Dissertation',
  'thesis': 'Thesis',
  'research-proposal': 'Research Proposal',
  'journal-article': 'Journal Article',
  'research-paper': 'Research Paper',
  'course-material': 'Course Material',
  'academic-guide': 'Academic Guide',
  'other': 'Other',
};

export const MOCK_RESOURCES: Resource[] = [
  {
    id: 'r-001',
    title: 'Machine Learning-Based System for Predicting Retail Product Prices',
    type: 'dissertation',
    author: 'Chilufya Mutale',
    authorId: 'u-s-002',
    school: 'School of Computing and Information Technology',
    programme: 'BSc Computer Science',
    course: 'Final Year Project',
    courseCode: 'COM401',
    academicYear: '2025/2026',
    dateUploaded: '2026-05-14',
    fileType: 'PDF',
    fileSize: '4.2 MB',
    description: 'A dissertation investigating the application of machine learning algorithms to predict retail product prices in the Zambian market context.',
    abstract: 'This dissertation investigates the application of supervised machine learning algorithms — specifically Random Forest, Gradient Boosting, and Long Short-Term Memory (LSTM) neural networks — to predict retail product prices in Zambia. Using a dataset of 50,000 transaction records collected from three major retail outlets in Lusaka, the study evaluates predictive accuracy and identifies key demand drivers. The proposed system achieves a Mean Absolute Percentage Error (MAPE) of 4.3%, outperforming baseline linear regression by 62%.',
    keywords: ['machine learning', 'price prediction', 'retail', 'LSTM', 'Zambia', 'data science'],
    status: 'published',
    downloads: 128,
    views: 394,
  },
  {
    id: 'r-002',
    title: 'COM322 Web Design and Development — Lecture Notes (Unit 1–6)',
    type: 'lecture-notes',
    author: 'Dr. Chanda Musonda',
    authorId: 'u-lecturer-1',
    school: 'School of Computing and Information Technology',
    programme: 'BSc Computer Science',
    course: 'Web Design and Development',
    courseCode: 'COM322',
    academicYear: '2025/2026',
    dateUploaded: '2026-02-03',
    fileType: 'PDF',
    fileSize: '8.7 MB',
    description: 'Comprehensive lecture notes covering HTML5, CSS3, JavaScript fundamentals, responsive design, and introductory React development.',
    keywords: ['web design', 'HTML5', 'CSS3', 'JavaScript', 'React', 'responsive design'],
    status: 'published',
    downloads: 312,
    views: 891,
  },
  {
    id: 'r-003',
    title: 'IT111 Introduction to Information Technology — Final Examination Paper 2024',
    type: 'past-paper',
    author: 'Dr. Mulenga Kalinda',
    authorId: 'u-l-002',
    school: 'School of Computing and Information Technology',
    programme: 'BSc Information Technology',
    course: 'Introduction to Information Technology',
    courseCode: 'IT111',
    academicYear: '2023/2024',
    dateUploaded: '2025-01-20',
    fileType: 'PDF',
    fileSize: '1.1 MB',
    description: 'Final examination paper for IT111, covering computer fundamentals, operating systems, networking basics, and information systems.',
    keywords: ['IT111', 'past paper', 'examination', 'information technology'],
    status: 'published',
    downloads: 487,
    views: 1203,
  },
  {
    id: 'r-004',
    title: 'Research Methodology for Computing Students — Academic Guide',
    type: 'academic-guide',
    author: 'Ms. Thandiwe Mwape',
    authorId: 'u-admin-1',
    school: 'School of Computing and Information Technology',
    programme: 'BSc Computer Science',
    academicYear: '2025/2026',
    dateUploaded: '2026-01-08',
    fileType: 'PDF',
    fileSize: '2.3 MB',
    description: 'A comprehensive guide to research methodology for final-year computing students, covering research design, data collection, analysis, and dissertation writing.',
    keywords: ['research methodology', 'dissertation', 'academic writing', 'research design'],
    status: 'published',
    downloads: 203,
    views: 577,
  },
  {
    id: 'r-005',
    title: 'IT211 Database Management Systems — Lecture Notes',
    type: 'lecture-notes',
    author: 'Dr. Chanda Musonda',
    authorId: 'u-lecturer-1',
    school: 'School of Computing and Information Technology',
    programme: 'BSc Information Technology',
    course: 'Database Management Systems',
    courseCode: 'IT211',
    academicYear: '2025/2026',
    dateUploaded: '2026-02-17',
    fileType: 'PDF',
    fileSize: '6.4 MB',
    description: 'Lecture notes on relational database theory, SQL, normalization, transactions, and NoSQL database systems.',
    keywords: ['database', 'SQL', 'normalization', 'NoSQL', 'relational database'],
    status: 'published',
    downloads: 274,
    views: 726,
  },
  {
    id: 'r-006',
    title: 'Student Academic Performance Prediction Using Artificial Intelligence',
    type: 'research-proposal',
    author: 'Mwansa Kapemba',
    authorId: 'u-student-1',
    school: 'School of Computing and Information Technology',
    programme: 'BSc Computer Science',
    course: 'Research Project',
    courseCode: 'COM401',
    academicYear: '2025/2026',
    dateUploaded: '2026-04-01',
    fileType: 'DOCX',
    fileSize: '0.9 MB',
    description: 'Research proposal investigating the use of AI and machine learning techniques to predict and improve student academic performance at Cavendish University Zambia.',
    keywords: ['academic performance', 'AI', 'prediction', 'student analytics', 'machine learning'],
    status: 'approved',
    downloads: 42,
    views: 118,
    abstract: 'This proposal outlines a study to develop an AI-based early warning system that identifies students at risk of academic failure. Using historical grade data, attendance records, and engagement metrics, a predictive model will be trained to provide targeted intervention recommendations.',
  },
  {
    id: 'r-007',
    title: 'BUS201 Principles of Management — Past Examination Paper 2025',
    type: 'past-paper',
    author: 'Mr. Kapambwe Mumba',
    authorId: 'u-l-003',
    school: 'School of Business',
    programme: 'BSc Business Administration',
    course: 'Principles of Management',
    courseCode: 'BUS201',
    academicYear: '2024/2025',
    dateUploaded: '2025-07-12',
    fileType: 'PDF',
    fileSize: '0.8 MB',
    description: 'Past examination paper covering organizational theory, leadership, motivation, and strategic management.',
    keywords: ['BUS201', 'management', 'past paper', 'leadership', 'examination'],
    status: 'published',
    downloads: 193,
    views: 521,
  },
  {
    id: 'r-008',
    title: 'Blockchain Technology for Land Title Registration in Zambia',
    type: 'dissertation',
    author: 'Bupe Nkonde',
    authorId: 'u-s-003',
    school: 'School of Computing and Information Technology',
    programme: 'BSc Information Technology',
    course: 'Final Year Project',
    courseCode: 'IT401',
    academicYear: '2024/2025',
    dateUploaded: '2025-05-22',
    fileType: 'PDF',
    fileSize: '3.8 MB',
    description: 'An investigation into how blockchain-based distributed ledger technology can modernize Zambia\'s land title registration system and reduce fraud.',
    keywords: ['blockchain', 'land registry', 'Zambia', 'distributed ledger', 'smart contracts'],
    status: 'published',
    downloads: 87,
    views: 263,
    abstract: 'Land title fraud and inefficient registration processes present significant challenges to Zambia\'s property market. This dissertation proposes a blockchain-based land title registry system, evaluating its technical feasibility, legal implications, and stakeholder readiness through mixed-methods research including interviews with officials from the Ministry of Lands.',
  },
  {
    id: 'r-009',
    title: 'COM301 Software Engineering — Lecture Notes and Case Studies',
    type: 'lecture-notes',
    author: 'Dr. Chanda Musonda',
    authorId: 'u-lecturer-1',
    school: 'School of Computing and Information Technology',
    programme: 'BSc Software Engineering',
    course: 'Software Engineering',
    courseCode: 'COM301',
    academicYear: '2025/2026',
    dateUploaded: '2026-01-28',
    fileType: 'PDF',
    fileSize: '11.2 MB',
    description: 'Comprehensive notes on software development lifecycle, agile methodologies, UML design, testing, and project management.',
    keywords: ['software engineering', 'agile', 'UML', 'SDLC', 'testing'],
    status: 'published',
    downloads: 341,
    views: 874,
  },
  {
    id: 'r-010',
    title: 'E-Commerce Adoption Among SMEs in Lusaka: Barriers and Enablers',
    type: 'research-paper',
    author: 'Dr. Mulenga Kalinda',
    authorId: 'u-l-002',
    school: 'School of Business',
    programme: 'BSc Business Administration',
    academicYear: '2025/2026',
    dateUploaded: '2026-03-05',
    fileType: 'PDF',
    fileSize: '1.7 MB',
    description: 'A peer-reviewed research paper examining the adoption rates and barriers to e-commerce among small and medium enterprises in Lusaka, Zambia.',
    keywords: ['e-commerce', 'SME', 'Lusaka', 'digital adoption', 'Zambia'],
    status: 'published',
    downloads: 156,
    views: 402,
    abstract: 'This paper presents findings from a survey of 120 SMEs in Lusaka regarding their e-commerce adoption. Results reveal that infrastructure cost, digital literacy, and consumer trust are the primary barriers, while mobile money integration and government incentive programmes are identified as key enablers.',
  },
  {
    id: 'r-011',
    title: 'COM201 Data Structures and Algorithms — Past Paper 2024',
    type: 'past-paper',
    author: 'Dr. Chanda Musonda',
    authorId: 'u-lecturer-1',
    school: 'School of Computing and Information Technology',
    programme: 'BSc Computer Science',
    course: 'Data Structures and Algorithms',
    courseCode: 'COM201',
    academicYear: '2023/2024',
    dateUploaded: '2025-02-10',
    fileType: 'PDF',
    fileSize: '0.7 MB',
    description: 'Final examination paper for COM201 covering sorting algorithms, trees, graphs, dynamic programming, and complexity analysis.',
    keywords: ['COM201', 'algorithms', 'data structures', 'past paper', 'examination'],
    status: 'published',
    downloads: 389,
    views: 1047,
  },
  {
    id: 'r-012',
    title: 'Cybersecurity Awareness and Practices Among University Students in Zambia',
    type: 'research-paper',
    author: 'Chisomo Phiri',
    authorId: 'u-s-004',
    school: 'School of Computing and Information Technology',
    programme: 'BSc Information Technology',
    academicYear: '2024/2025',
    dateUploaded: '2025-04-18',
    fileType: 'PDF',
    fileSize: '2.1 MB',
    description: 'A quantitative study on cybersecurity awareness levels, password practices, and phishing vulnerability among university students in Zambia.',
    keywords: ['cybersecurity', 'awareness', 'students', 'Zambia', 'information security'],
    status: 'published',
    downloads: 74,
    views: 221,
  },
];

export const MOCK_SUBMISSIONS: Submission[] = [
  {
    id: 'sub-001',
    title: 'Student Academic Performance Prediction Using Artificial Intelligence',
    studentId: 'u-student-1',
    studentName: 'Mwansa Kapemba',
    studentEmail: 'mwansa.kapemba@students.cavendish.ac.zm',
    programme: 'BSc Computer Science',
    school: 'School of Computing and Information Technology',
    type: 'research-proposal',
    submittedDate: '2026-04-01',
    status: 'approved',
    reviewerId: 'u-lecturer-1',
    reviewerName: 'Dr. Chanda Musonda',
    reviewerFeedback: 'Well-structured proposal with a clear research problem and appropriate methodology. Approved for the repository.',
    academicYear: '2025/2026',
    course: 'Final Year Project',
    fileType: 'DOCX',
    fileSize: '0.9 MB',
    abstract: 'This proposal outlines a study to develop an AI-based early warning system that identifies students at risk of academic failure.',
    keywords: ['AI', 'academic performance', 'prediction', 'machine learning'],
  },
  {
    id: 'sub-002',
    title: 'Final Year Dissertation: Smart Campus IoT Management System',
    studentId: 'u-student-1',
    studentName: 'Mwansa Kapemba',
    studentEmail: 'mwansa.kapemba@students.cavendish.ac.zm',
    programme: 'BSc Computer Science',
    school: 'School of Computing and Information Technology',
    type: 'dissertation',
    submittedDate: '2026-05-30',
    status: 'under-review',
    academicYear: '2025/2026',
    course: 'Final Year Project',
    courseCode: 'COM401',
    fileType: 'PDF',
    fileSize: '5.6 MB',
    abstract: 'This dissertation proposes and evaluates a Smart Campus IoT Management System for Cavendish University Zambia, integrating sensor networks, real-time dashboards, and predictive maintenance alerts.',
    keywords: ['IoT', 'smart campus', 'sensor networks', 'automation', 'university'],
  },
  {
    id: 'sub-003',
    title: 'Research Methods in Computer Science — Literature Review',
    studentId: 'u-student-1',
    studentName: 'Mwansa Kapemba',
    studentEmail: 'mwansa.kapemba@students.cavendish.ac.zm',
    programme: 'BSc Computer Science',
    school: 'School of Computing and Information Technology',
    type: 'research-paper',
    submittedDate: '2026-02-12',
    status: 'rejected',
    reviewerId: 'u-lecturer-1',
    reviewerName: 'Dr. Chanda Musonda',
    reviewerFeedback: 'The literature review lacks sufficient depth and does not engage with recent publications (2022–2026). Please revise the review to include at least 15 peer-reviewed sources published within the last 4 years and strengthen your critical analysis of each source.',
    academicYear: '2025/2026',
    fileType: 'DOCX',
    fileSize: '1.2 MB',
  },
  {
    id: 'sub-004',
    title: 'Mobile Banking Security Vulnerabilities in Zambia',
    studentId: 'u-s-005',
    studentName: 'Namwaka Chisanga',
    studentEmail: 'namwaka.chisanga@students.cavendish.ac.zm',
    programme: 'BSc Information Technology',
    school: 'School of Computing and Information Technology',
    type: 'research-proposal',
    submittedDate: '2026-06-02',
    status: 'submitted',
    academicYear: '2025/2026',
    course: 'Research Project',
    courseCode: 'IT401',
    fileType: 'PDF',
    fileSize: '1.4 MB',
    abstract: 'This proposal aims to investigate and document security vulnerabilities in mobile banking applications used in Zambia, proposing countermeasures and best practices.',
    keywords: ['mobile banking', 'security', 'Zambia', 'fintech', 'vulnerabilities'],
  },
  {
    id: 'sub-005',
    title: 'Impact of Social Media on Academic Performance of University Students',
    studentId: 'u-s-006',
    studentName: 'Musonda Zulu',
    studentEmail: 'musonda.zulu@students.cavendish.ac.zm',
    programme: 'BSc Business Administration',
    school: 'School of Business',
    type: 'research-paper',
    submittedDate: '2026-06-05',
    status: 'under-review',
    reviewerId: 'u-lecturer-1',
    reviewerName: 'Dr. Chanda Musonda',
    academicYear: '2025/2026',
    fileType: 'PDF',
    fileSize: '2.0 MB',
    abstract: 'This paper investigates the relationship between social media usage and academic performance among undergraduate students at Cavendish University Zambia.',
    keywords: ['social media', 'academic performance', 'students', 'university'],
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n-001',
    userId: 'u-student-1',
    title: 'Research Proposal Approved',
    message: 'Your research proposal "Student Academic Performance Prediction Using AI" has been approved by Dr. Chanda Musonda and is now published in the repository.',
    type: 'success',
    read: false,
    date: '2026-04-05',
    actionView: 'my-submissions',
  },
  {
    id: 'n-002',
    userId: 'u-student-1',
    title: 'Submission Requires Revision',
    message: 'Your submission "Research Methods in Computer Science — Literature Review" has been reviewed. Please see the reviewer feedback and resubmit.',
    type: 'warning',
    read: false,
    date: '2026-02-20',
    actionView: 'my-submissions',
  },
  {
    id: 'n-003',
    userId: 'u-student-1',
    title: 'New Past Paper Available',
    message: 'A new past examination paper for COM201 Data Structures and Algorithms (2024) has been uploaded to the repository.',
    type: 'info',
    read: true,
    date: '2026-02-10',
    actionView: 'repository',
  },
  {
    id: 'n-004',
    userId: 'u-student-1',
    title: 'New Lecture Notes — COM322',
    message: 'Dr. Chanda Musonda has uploaded new lecture notes for COM322 Web Design and Development (Units 1–6).',
    type: 'info',
    read: true,
    date: '2026-02-03',
    actionView: 'repository',
  },
  {
    id: 'n-005',
    userId: 'u-lecturer-1',
    title: 'New Student Submission',
    message: 'Namwaka Chisanga has submitted a research proposal "Mobile Banking Security Vulnerabilities in Zambia" for review.',
    type: 'info',
    read: false,
    date: '2026-06-02',
    actionView: 'review-submissions',
  },
  {
    id: 'n-006',
    userId: 'u-lecturer-1',
    title: 'New Student Submission',
    message: 'Musonda Zulu has submitted "Impact of Social Media on Academic Performance of University Students" for review.',
    type: 'info',
    read: false,
    date: '2026-06-05',
    actionView: 'review-submissions',
  },
];

export const MONTHLY_UPLOADS = [
  { month: 'Jan', uploads: 18 },
  { month: 'Feb', uploads: 34 },
  { month: 'Mar', uploads: 27 },
  { month: 'Apr', uploads: 41 },
  { month: 'May', uploads: 38 },
  { month: 'Jun', uploads: 52 },
  { month: 'Jul', uploads: 29 },
  { month: 'Aug', uploads: 17 },
];

export const MONTHLY_DOWNLOADS = [
  { month: 'Jan', downloads: 342 },
  { month: 'Feb', downloads: 518 },
  { month: 'Mar', downloads: 487 },
  { month: 'Apr', downloads: 623 },
  { month: 'May', downloads: 791 },
  { month: 'Jun', downloads: 834 },
  { month: 'Jul', downloads: 619 },
  { month: 'Aug', downloads: 241 },
];

export const CATEGORY_STATS = [
  { name: 'Lecture Notes', count: 48, color: '#0f2e6b' },
  { name: 'Past Papers', count: 62, color: '#1d4ed8' },
  { name: 'Dissertations', count: 37, color: '#3568ae' },
  { name: 'Research Papers', count: 24, color: '#5a8ac4' },
  { name: 'Course Materials', count: 31, color: '#8eb0d9' },
  { name: 'Theses', count: 19, color: '#bdd0eb' },
];

export const ALL_USERS: User[] = [
  ...DEMO_USERS,
  {
    id: 'u-s-002',
    name: 'Chilufya Mutale',
    email: 'chilufya.mutale@students.cavendish.ac.zm',
    role: 'student',
    studentId: 'CUZ/2022/IT/0089',
    programme: 'BSc Information Technology',
    school: 'School of Computing and Information Technology',
    yearOfStudy: 4,
    status: 'active',
    dateJoined: '2022-08-15',
    submissionsCount: 1,
    downloadsCount: 34,
    bookmarksCount: 8,
  },
  {
    id: 'u-s-003',
    name: 'Bupe Nkonde',
    email: 'bupe.nkonde@students.cavendish.ac.zm',
    role: 'student',
    studentId: 'CUZ/2021/IT/0056',
    programme: 'BSc Information Technology',
    school: 'School of Computing and Information Technology',
    yearOfStudy: 4,
    status: 'active',
    dateJoined: '2021-08-10',
    submissionsCount: 2,
    downloadsCount: 61,
    bookmarksCount: 15,
  },
  {
    id: 'u-s-004',
    name: 'Chisomo Phiri',
    email: 'chisomo.phiri@students.cavendish.ac.zm',
    role: 'student',
    studentId: 'CUZ/2022/IT/0104',
    programme: 'BSc Information Technology',
    school: 'School of Computing and Information Technology',
    yearOfStudy: 3,
    status: 'active',
    dateJoined: '2022-08-15',
    submissionsCount: 1,
    downloadsCount: 22,
    bookmarksCount: 5,
  },
  {
    id: 'u-s-005',
    name: 'Namwaka Chisanga',
    email: 'namwaka.chisanga@students.cavendish.ac.zm',
    role: 'student',
    studentId: 'CUZ/2023/IT/0178',
    programme: 'BSc Information Technology',
    school: 'School of Computing and Information Technology',
    yearOfStudy: 3,
    status: 'active',
    dateJoined: '2023-08-20',
    submissionsCount: 1,
    downloadsCount: 19,
    bookmarksCount: 7,
  },
  {
    id: 'u-s-006',
    name: 'Musonda Zulu',
    email: 'musonda.zulu@students.cavendish.ac.zm',
    role: 'student',
    studentId: 'CUZ/2023/BA/0067',
    programme: 'BSc Business Administration',
    school: 'School of Business',
    yearOfStudy: 3,
    status: 'active',
    dateJoined: '2023-08-20',
    submissionsCount: 1,
    downloadsCount: 31,
    bookmarksCount: 4,
  },
  {
    id: 'u-l-002',
    name: 'Dr. Mulenga Kalinda',
    email: 'm.kalinda@cavendish.ac.zm',
    role: 'lecturer',
    staffId: 'CUZ/STF/0051',
    department: 'Department of Computing',
    school: 'School of Computing and Information Technology',
    status: 'active',
    dateJoined: '2019-07-01',
  },
  {
    id: 'u-l-003',
    name: 'Mr. Kapambwe Mumba',
    email: 'k.mumba@cavendish.ac.zm',
    role: 'lecturer',
    staffId: 'CUZ/STF/0062',
    department: 'Department of Business Studies',
    school: 'School of Business',
    status: 'active',
    dateJoined: '2020-01-15',
  },
];
